#!/usr/bin/env python3
"""ghidra_funcs_to_reference.py — build a labels-only reference .s from a
Ghidra decompiled-C export directory (ExportDecompiledAll.java output:
one FUN_XXXXXXXX.c per function).

The eval tool's reference loader only consumes `FUN_<addr>:` labels from
.s files in `reference_dir`; the disassembly text itself is never parsed
(same-module static callers are scanned from raw binary bytes).  So a
stub .s with one label per Ghidra function gives the eval tool the full
Ghidra function-boundary database as its second opinion, without
exporting actual disassembly from Ghidra.

Address sources, in order:
  1. `FUN_<addr>.c` filenames
  2. the header comment `/* <name>  0x<addr> */` ExportDecompiledAll
     writes on line 1 (covers functions renamed inside Ghidra)

Files with neither (typically stale renamed duplicates of a FUN_ file)
are reported and skipped.

Usage:
    python ghidra_funcs_to_reference.py <ghidra_reference_dir> <out.s>

Re-run whenever the Ghidra database improves (after re-running
ExportDecompiledAll.java) to refresh the eval tool's second opinion.
"""

import re
import sys
from pathlib import Path

FILENAME_RE = re.compile(r"FUN_([0-9A-Fa-f]{8})\.c\Z")
HEADER_RE = re.compile(r"/\*\s*\S+\s+0x([0-9A-Fa-f]{8})\s*\*/")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(2)
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    if not src.is_dir():
        print(f"ERROR: {src} is not a directory")
        sys.exit(2)

    addrs = set()
    skipped = []
    for f in sorted(src.glob("*.c")):
        m = FILENAME_RE.search(f.name)
        if m:
            addrs.add(int(m.group(1), 16))
            continue
        head = f.read_text(errors="replace")[:400]
        m = HEADER_RE.search(head)
        if m:
            addrs.add(int(m.group(1), 16))
        else:
            skipped.append(f.name)

    if not addrs:
        print(f"ERROR: no function addresses found in {src}")
        sys.exit(1)

    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="\n") as fp:
        fp.write(
            "/* Ghidra function-boundary reference — labels only.\n"
            f" * Generated by ghidra_funcs_to_reference.py from {src.name}/\n"
            f" * ({len(addrs)} functions).  The eval tool reads FUN_<addr>:\n"
            " * labels from this file; there is intentionally no code here.\n"
            " * Regenerate after re-running ExportDecompiledAll.java.\n"
            " */\n\n"
        )
        for a in sorted(addrs):
            fp.write(f"FUN_{a:08X}:\n")

    print(f"{out}: {len(addrs)} FUN_ labels")
    if skipped:
        print(f"skipped {len(skipped)} file(s) with no derivable address "
              f"(stale renamed duplicates?): {', '.join(skipped[:10])}")


if __name__ == "__main__":
    main()
